heat_template_version: 2016-04-08

description: >
  Extra hostname configuration

parameters:
  servers:
    type: json

resources:
  ExtraConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
#      inputs:
#      - name: foo
#      - name: bar
#      outputs:
#      - name: result
      config: |
        #!/bin/sh
        echo "$(hostname)" >> /var/log/scaleio.log

  ExtraDeployments:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ExtraConfig}
#      actions: ['CREATE','UPDATE']
#      input_values:
#        foo: fooooo
