heat_template_version: 2016-04-08

description: >
  Extra ScaleIO configuration

parameters:
  server:
    description: ID of the controller node to apply this config to
    type: string

resources:

  ScaleIOPrepareConfig:
    type: OS::ScaleIO::ScaleIODeploymentData
    properties:
      server: {get_param: server}

  ExtraConfigFile:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: 01_install_packages.sh

  ScaleIODeployment_InstallPackages:
    type: OS::Heat::SoftwareDeployment
    depends_on: ScaleIOPrepareConfig
    properties:
      name: ScaleIODeployment_InstallPackages
      config: {get_resource: ExtraConfigFile}
      server: {get_param: server}

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger puppet apply on changes
    value: {get_attr: [ScaleIODeployment_InstallPackages, deploy_stdout]}
