heat_template_version: 2016-04-08

description: >
  Parameters for deploying an ScaleIO over OpenStack environment.

parameters:

  servers:
    type: json

  PuppetsVersion:
    type: string
    default: "master"
    description: Use specific puppet modules from puppet forge or use latest from upstream.
  PackagesSourceURL:
    type: string
    description: Where to get packages of ScaleIO for installation.
  ScaleIODriverFTP:
    type: string
    default: "ftp://QNzgdxXix:Aw3wFAwAq3@ftp.emc.com"
    description: |
      URL for driver_sync.sh script from sdc/xcache packages to sync & verify driver.

  RolesForSDS:
    type: string
    default: blockstorage
    description: Comma separated list of roles to insall SDS on.
  GatewayPort:
    type: number
    default: 4443
    description: Port where gateway will listen.

  ScaleIOAdminPassword:
    type: string
    default: "Default_password"
    description: "MDM password for admin"
  ScaleIOClientPassword:
    type: string
    default: "Client_password"
    description: "Password for scaleio_client user that will be used for openstack services"

  DevicePaths:
    type: string
    description: Comma separated list of devices, e.g. /dev/sdb,/dev/sdc.


  ProtectionDomain:
    type: string
    default: default
    description: Name of first protection domain. Next domains will get names like default_2, default_3.
  ProtectionDomainNodes:
    type: number
    default: 100
    description: >
        If number of nodes gets lasrgert than this threshould new protection domain will be created.
        Note, in that case it is needed to add at least 3 new nodes with Storage role to make new domain operationable.
  StoragePools:
    type: string
    default: default
    description: >
        Comma separated list for splitting devices between them.
        It could be just one element if all devices are belong to the one pool.
  ProvisioningType:
    type: string
    default: thin
    description: Thin/Thick provisioning for ephemeral and persistent volumes.

  UseScaleioForGlance:
    type: boolean
    default: false
    description: Glance uses ScaleIO as a backend for images if the option enabled. It uses cinder backend in Glance to store images on ScaleIO.

  ChecksumMode:
    type: boolean
    default: false
    description: >
        Checksum protection. ScaleIO protects data in-flight by calculating and validating the checksum value for the payload at both ends.
        Note, the checksum feature may have a minor effect on performance.
        ScaleIO utilizes hardware capabilities for this feature, where possible.
  SparePolicy:
    type: number
    default: 10
    description: "Spare policy: % out of total space."
  ZeroPadding:
    type: boolean
    default: true
    description: "Enable Zero Padding for Storage Pools. New volumes will be zeroed if the option enabled."
  ScannerMode:
    type: boolean
    default: false
    description: "Background device scanner. This options enables the background device scanner on the devices in device only mode."
  RMCachePassthroughPools:
    type: string
    default: ""
    description: "List of Storage pools which should be cached in RAM in passthrough mode (writes to storage only)."
  RMCacheCachedPools:
    type: string
    default: ""
    description: "List of Storage pools which should be cached in RAM in cached mode (writes both to cache and to storage)."
  RFCacheDevices:
    type: string
    default: ""
    description: "List of SDS devices for SSD caching. Cache is disabled if list empty."
  RFCacheCachedPools:
    type: string
    default: ""
    description: "List of Storage pools which should be cached on SSD."

resources:
  ScaleIOConfigData:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: PuppetsVersion
      - name: PackagesSourceURL
      - name: ScaleIODriverFTP
      - name: RolesForSDS
      - name: GatewayPort
      - name: ScaleIOAdminPassword
      - name: ScaleIOClientPassword
      - name: DevicePaths
      - name: ProtectionDomain
      - name: ProtectionDomainNodes
      - name: StoragePools
      - name: ProvisioningType
      - name: UseScaleioForGlance
      - name: ChecksumMode
      - name: SparePolicy
      - name: ZeroPadding
      - name: ScannerMode
      - name: RMCachePassthroughPools
      - name: RMCacheCachedPools
      - name: RFCacheDevices
      - name: RFCacheCachedPools

      config: |
        #!/bin/bash -e
        FILE='/etc/scaleio.env'
        rm -f $FILE
        echo "export PuppetsVersion='$PuppetsVersion'" >> $FILE
        echo "export PackagesSourceURL='$PackagesSourceURL'" >> $FILE
        echo "export ScaleIODriverFTP='$ScaleIODriverFTP'" >> $FILE
        echo "export RolesForSDS='$RolesForSDS'" >> $FILE
        echo "export GatewayPort='$GatewayPort'" >> $FILE
        echo "export ScaleIOAdminPassword='$ScaleIOAdminPassword'" >> $FILE
        echo "export ScaleIOClientPassword='$ScaleIOClientPassword'" >> $FILE
        echo "export DevicePaths='$DevicePaths'" >> $FILE
        echo "export ProtectionDomain='$ProtectionDomain'" >> $FILE
        echo "export ProtectionDomainNodes='$ProtectionDomainNodes'" >> $FILE
        echo "export StoragePools='$StoragePools'" >> $FILE
        echo "export ProvisioningType='$ProvisioningType'" >> $FILE
        echo "export UseScaleioForGlance='$UseScaleioForGlance'" >> $FILE
        echo "export ChecksumMode='$ChecksumMode'" >> $FILE
        echo "export SparePolicy='$SparePolicy'" >> $FILE
        echo "export ZeroPadding='$ZeroPadding'" >> $FILE
        echo "export ScannerMode='$ScannerMode'" >> $FILE
        echo "export RMCachePassthroughPools='$RMCachePassthroughPools'" >> $FILE
        echo "export RMCacheCachedPools='$RMCacheCachedPools'" >> $FILE
        echo "export RFCacheDevices='$RFCacheDevices'" >> $FILE
        echo "export RFCacheCachedPools='$RFCacheCachedPools'" >> $FILE
        cat $FILE

  ScaleIODeploymentData:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ScaleIOConfigData}
      input_values:
        PuppetsVersion: {get_param: PuppetsVersion}
        PackagesSourceURL: {get_param: PackagesSourceURL}
        ScaleIODriverFTP: {get_param: ScaleIODriverFTP}
        RolesForSDS: {get_param: RolesForSDS}
        GatewayPort: {get_param: GatewayPort}
        ScaleIOAdminPassword: {get_param: ScaleIOAdminPassword}
        ScaleIOClientPassword: {get_param: ScaleIOClientPassword}
        DevicePaths: {get_param: DevicePaths}
        ProtectionDomain: {get_param: ProtectionDomain}
        ProtectionDomainNodes: {get_param: ProtectionDomainNodes}
        StoragePools: {get_param: StoragePools}
        ProvisioningType: {get_param: ProvisioningType}
        UseScaleioForGlance: {get_param: UseScaleioForGlance}
        ChecksumMode: {get_param: ChecksumMode}
        SparePolicy: {get_param: SparePolicy}
        ZeroPadding: {get_param: ZeroPadding}
        ScannerMode: {get_param: ScannerMode}
        RMCachePassthroughPools: {get_param: RMCachePassthroughPools}
        RMCacheCachedPools: {get_param: RMCacheCachedPools}
        RFCacheDevices: {get_param: RFCacheDevices}
        RFCacheCachedPools: {get_param: RFCacheCachedPools}
