heat_template_version: 2016-04-08

description: >
  Extra ScaleIO configuration

parameters:
  servers:
    type: json
  DeployIdentifier:
    type: string
    description: Value which changes if the node configuration may need to be re-applied

resources:

  ScaleIOPrepareConfig:
    type: OS::ScaleIO::ScaleIODeploymentData
    properties:
      servers:  {get_param: servers}

  ExtraConfigFile1:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: 01_prepare_repo.sh
  ScaleIODeployment_Step01:
    type: OS::Heat::SoftwareDeployments
    depends_on: ScaleIOPrepareConfig
    properties:
      name: ScaleIODeployment_Step01
      servers:  {get_param: servers}
      config: {get_resource: ExtraConfigFile1}
      input_values:
        update_identifier: {get_param: DeployIdentifier}

  ExtraConfigFile2:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: 02_install_packages.sh
  ScaleIODeployment_Step02:
    type: OS::Heat::SoftwareDeployments
    depends_on: ScaleIODeployment_Step01
    properties:
      name: ScaleIODeployment_Step02
      servers:  {get_param: servers}
      config: {get_resource: ExtraConfigFile2}
      input_values:
        update_identifier: {get_param: DeployIdentifier}


  ExtraConfigFile3:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: 03_configure_cluster.sh
  ScaleIODeployment_Step03:
    type: OS::Heat::SoftwareDeployments
    depends_on: ScaleIODeployment_Step02
    properties:
      name: ScaleIODeployment_Step03
      servers:  {get_param: servers}
      config: {get_resource: ExtraConfigFile3}
      input_values:
        update_identifier: {get_param: DeployIdentifier}

  # TODO: configure SDC, configure OpenStack services


  # Note, this should come last, so use depends_on to ensure
  # this is created after any other resources.
  ExtraDeployments:
    type: OS::Heat::None
    depends_on: ScaleIODeployment_Step03
