heat_template_version: 2016-04-08

description: >
  Extra ScaleIO configuration

parameters:
  servers:
    type: json
  DeployIdentifier:
     type: string
     description: Value which changes if the node configuration may need to be re-applied
  RoleData:
    type: json
    default: {}

resources:

  ExtraConfigFile:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: file
      config:
        get_file: {get_param: file}

  ScaleIODeployment_Step01:
    type: OS::Heat::SoftwareDeployments
    depends_on: ScaleIODeploymentData
    properties:
      name: ScaleIODeployment_Step01
      servers:  {get_param: servers}
      config: {get_resource: ExtraConfigFile}
      input_values:
        file: 01_prepare_repo.sh
        update_identifier: {get_param: DeployIdentifier}

  ScaleIODeployment_Step02:
    type: OS::Heat::SoftwareDeployments
    depends_on: ScaleIODeployment_Step01
    properties:
      name: ScaleIODeployment_Step02
      servers:  {get_param: servers}
      config: {get_resource: ExtraConfigFile}
      input_values:
        file: 02_install_puppets.sh
        update_identifier: {get_param: DeployIdentifier}


  # Note, this should come last, so use depends_on to ensure
  # this is created after any other resources.
  ExtraDeployments:
    type: OS::Heat::None
    depends_on: ScaleIODeployment_Step02
