heat_template_version: 2016-04-08

description: >
  Extra ScaleIO configuration

parameters:
  controller_servers:
    type: json
  compute_servers:
    type: json
  blockstorage_servers:
    type: json
  objectstorage_servers:
    type: json
  cephstorage_servers:
    type: json

resources:

  ScaleIOPrepareConfigController:
    type: OS::ScaleIO::ScaleIODeploymentData
    properties:
      servers: {get_param: controller_servers}
  ScaleIOPrepareConfigCompute:
    type: OS::ScaleIO::ScaleIODeploymentData
    properties:
      servers: {get_param: compute_servers}
  ScaleIOPrepareConfigBlockStorage:
    type: OS::ScaleIO::ScaleIODeploymentData
    properties:
      servers: {get_param: blockstorage_servers}

  ExtraConfigFile1:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: role
      config:
        get_file: 01_install_packages.sh
  ScaleIODeployment_Step01Controller:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ScaleIOPrepareConfigController
    properties:
      servers: {get_param: controller_servers}
      config: {get_resource: ExtraConfigFile1}
      input_values:
        role: controller
  ScaleIODeployment_Step01Compute:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ScaleIOPrepareConfigCompute
    properties:
      servers: {get_param: compute_servers}
      config: {get_resource: ExtraConfigFile1}
      input_values:
        role: compute
  ScaleIODeployment_Step01BlockStorage:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ScaleIOPrepareConfigBlockStorage
    properties:
      servers: {get_param: blockstorage_servers}
      config: {get_resource: ExtraConfigFile1}
      input_values:
        role: blockstorage

  ExtraConfigFile2:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: 02_create_cluster.sh
  ScaleIODeployment_Step02:
    type: OS::Heat::SoftwareDeployment
    depends_on: [ScaleIODeployment_Step01Controller, ScaleIODeployment_Step01Compute, ScaleIODeployment_Step01BlockStorage]
    properties:
      # TODO: run it on all controllers to add all MDM's to cluster
      server: {get_param: [controller_servers, '0']}
      config: {get_resource: ExtraConfigFile2}

  ExtraConfigFile3:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: 03_configure_cluster.sh
  ScaleIODeployment_Step03:
    type: OS::Heat::SoftwareDeployment
    depends_on: ScaleIODeployment_Step02
    properties:
      server: {get_param: [controller_servers, '0']}
      config: {get_resource: ExtraConfigFile3}

  ExtraConfigFile4:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: 04_configure_controllers.sh
  ScaleIODeployment_Step04:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ScaleIODeployment_Step03
    properties:
      server: {get_param: controller_servers}
      config: {get_resource: ExtraConfigFile4}

  ExtraConfigFile5:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: role
      config:
        get_file: 05_configure_clients.sh
  ScaleIODeployment_Step05Controller:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ScaleIODeployment_Step04
    properties:
      server: {get_param: controller_servers}
      config: {get_resource: ExtraConfigFile5}
      input_values:
        role: controller
  ScaleIODeployment_Step05Compute:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ScaleIODeployment_Step04
    properties:
      server: {get_param: compute_servers}
      config: {get_resource: ExtraConfigFile5}
      input_values:
        role: compute
  ScaleIODeployment_Step05BlockStorage:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ScaleIODeployment_Step04
    properties:
      server: {get_param: blockstorage_servers}
      config: {get_resource: ExtraConfigFile5}
      input_values:
        role: blockstorage
