heat_template_version: 2016-04-08

description: >
  SwapOn configuration

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: swapon_config}

  swapon_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        swap_device=$(sudo fdisk -l | grep swap | awk '{print $1}')
        if [[ -n "$swap_device" ]]; then
          rc_local="/etc/rc.d/rc.local"
          echo "swapon $swap_device" >> $rc_local
          chmod 755 $rc_local
          swapon $swap_device
        fi

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
